swagger: '2.0'
info:
  version: 1.0.0
  title: Kafka Janitor
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api/
paths:
  /topics:
    get:
      summary: Returns a list of topics
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              name:
                type: string
                example: build.capabilities
              partitions:
                type: number
                example: 12
    post:
      summary: Create a new topic
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                example: capability-name.aggregate-name-in-plural
              partitions:
                type: string
          description: ''
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              name:
                type: string
                example: build.capabilities
              partitions:
                type: number
                example: 12
        '409':
          description: Conflict
          schema:
            type: object
            properties:
              message:
                type: string
                example: Topic already exists.
  /access/request:
    post:
      summary: ''
      operationId: post-access-request
      responses:
        '200':
          description: OK
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              capabilityName:
                type: string
              capabilityId:
                type: string
              capabilityRootId:
                type: string                
definitions:
  topic:
    type: object
    properties:
      name:
        type: string
        example: build.capabilities
      partitions:
        type: number
        example: 12