name: $(Build.BuildId)
pool: Docker-pool
trigger:
  - master

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.100
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - bash: |
      make release BUILD_NUMBER=$(Build.BuildId)
    env:
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    displayName: 'Build, create and upload container image'

  - bash: |
      chmod +x alcide.sh
      ./alcide.sh
    displayName: 'Run Alcide scans'

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: k8s manifests"
    inputs:
      PathtoPublish: k8s
      ArtifactName: manifests