version: "3.8"

services:
  database:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -U postgres"
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 30s

  db-migration:
    build: ./db
    depends_on:
      database:
        condition: service_healthy
    environment:
      - LOCAL_DEVELOPMENT=1 # will try to CREATE DATABASE ${PGDATABASE}
      - PGDATABASE=postgres # database name
      - PGHOST=database # same as above - docker-compose service name
      - PGPORT=5432 # same as above
      - PGUSER=postgres # same as above
      - PGPASSWORD=p # same as above
      - PGSSLMODE=disable # ignore SSLMODE for local development (overwritten - see ./db/Dockerfile)