apiVersion: v1
kind: Service
metadata:
  labels:
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
    app: {{ include "kafkajanitor.fullname" . }}
    component: kafka-janitor
    scrape-service-metrics: "true"
  name: {{ include "kafkajanitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: external
    port: 80
    targetPort: 5000
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: {{ include "kafkajanitor.fullname" . }}
  type: ClusterIP
