apiVersion: v1
kind: Service
metadata:
  name: kafka-janitor
  namespace: selfservice
  labels:
    app: kafka-janitor
    project: selfservice
    department: devex
    component: kafka-janitor
    scrape-service-metrics: "true"
spec:
  ports:
  - name: external
    port: 80
    targetPort: 5000
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: kafka-janitor