{
 "title": "Kafka-Janitor - In depth",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Healthcheck - Tika",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Tika\", status=~\"healthy\"}) * 2 + sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Tika\", status=~\"degraded\"})",
     "legendFormat": "Tika"
    }
   ]
  },
  {
   "title": "Healthcheck - Vault",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Vault\", status=~\"healthy\"}) * 2 + sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Vault\", status=~\"degraded\"})",
     "legendFormat": "Tika"
    }
   ]
  },
  {
   "title": "Healthcheck - assembly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(healthcheck{service=\"kafka-janitor\", exported_service=\"assembly\", status=~\"healthy\"}) * 2 + sum(healthcheck{service=\"kafka-janitor\", exported_service=\"assembly\", status=~\"degraded\"})",
     "legendFormat": "assembly"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=~\"selfservice.*\",service=\"kafka-janitor\"}[5m])) by (service) / sum(rate(http_request_duration_seconds_count{namespace=~\"selfservice.*\",service=\"kafka-janitor\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Health check duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max(healthcheck_duration_seconds{service=\"kafka-janitor\",namespace=\"selfservice\"}) by (exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Health check",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Tika\", status=~\"healthy\"}) * 2 + sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Tika\", status=~\"degraded\"})",
     "legendFormat": "Tika"
    },
    {
     "expr": "sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Vault\", status=~\"healthy\"}) * 2 + sum(healthcheck{service=\"kafka-janitor\", exported_service=\"Vault\", status=~\"degraded\"})",
     "legendFormat": "Vault"
    },
    {
     "expr": "sum(healthcheck{service=\"kafka-janitor\", exported_service=\"assembly\", status=~\"healthy\"}) * 2 + sum(healthcheck{service=\"kafka-janitor\", exported_service=\"assembly\", status=~\"degraded\"})",
     "legendFormat": "assembly"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 19 } }
 ]
}