apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika-lkc-4npj6
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
    app: tika
    component: tika
    version: 0.0.1
    cluster: lkc-4npj6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
      cluster: lkc-4npj6
  template:
    metadata:
      labels:
        logging_dfds_cloud_format_json: "false"
        app: tika
        project: selfservice
        department: devex
        cluster: lkc-4npj6
    spec:
      priorityClassName: selfservice
      containers:
      - name: tika-lkc-4npj6
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/tika:361804
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "700m"
        env:
        - name: TIKA_CCLOUD_ENVIRONMENT_ID
          value: t4332        
        - name: TIKA_CCLOUD_CLUSTER_ID
          value: lkc-4npj6
        - name: TIKA_CC_USER
          valueFrom:
            secretKeyRef:
              name: tika-confluent
              key: TIKA_CC_USER
        - name: TIKA_CC_PASS
          valueFrom:
            secretKeyRef:
              name: tika-confluent
              key: TIKA_CC_PASS
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
          httpGet:
            port: 3000
            path: /healthz
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            port: 3000
            path: /healthz