apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-janitor
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
    app: kafka-janitor
    component: kafka-janitor
    app.kubernetes.io/version: "0.0.1"
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true
  replicas: 1
  selector:
    matchLabels:
      app: kafka-janitor
  template:
    metadata:
      labels:
        app: kafka-janitor
        project: selfservice
        department: devex
      annotations:
        iam.amazonaws.com/role: PutKafkaParameter
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      containers:
      - name: kafka-janitor
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/kafka-janitor:$(Build.BuildId)
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
        ports:
        - containerPort: 5000
          name: web
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: TIKA_API_ENDPOINT
          value: "http://localhost:3000"
        - name: KAFKA_JANITOR_BOOTSTRAP_SERVERS
          value: $(KAFKA_BOOTSTRAP_SERVERS)
        - name: KAFKA_JANITOR_GROUP_ID
          value: build.selfservice.kafka-janitor-consumer
        - name: KAFKA_JANITOR_BROKER_VERSION_FALLBACK
          value: "0.10.0.0"
        - name: KAFKA_JANITOR_API_VERSION_FALLBACK_MS
          value: "0"
        - name: KAFKA_JANITOR_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-janitor
              key: SASL_USERNAME
        - name: KAFKA_JANITOR_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-janitor
              key: SASL_PASSWORD
        - name: KAFKA_JANITOR_SASL_MECHANISMS
          value: "PLAIN"
        - name: KAFKA_JANITOR_SECURITY_PROTOCOL
          value: "SASL_SSL"
        - name: KAFKAJANITOR_VAULT
          value: "AWS_SSM"
        - name: ASPNETCORE_URLS
          value: http://+:5000
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
      - name: tika
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/tika:223930
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: TIKA_CCLOUD_CLUSTER_ID
          value: $(TIKA_CCLOUD_CLUSTER_ID)
        - name: TIKA_CC_USER
          valueFrom:
            secretKeyRef:
              name: tika-confluent
              key: TIKA_CC_USER
        - name: TIKA_CC_PASS
          valueFrom:
            secretKeyRef:
              name: tika-confluent
              key: TIKA_CC_PASS
