apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-janitor
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
    app: kafka-janitor
    component: kafka-janitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-janitor
  template:
    metadata:
      labels:
        app: kafka-janitor
        project: selfservice
        department: devex
      # annotations:
      #   prometheus.io/port: "8080"
      #   prometheus.io/scrape: "true"
    spec:
      containers:
      - name: kafka-janitor
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/kafka-janitor:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        # - containerPort: 8080
        #   name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: KAFKA_JANITOR_BOOTSTRAP_SERVERS
          value: $(KAFKA_BOOTSTRAP_SERVERS)
        - name: KAFKA_JANITOR_GROUP_ID
          value: build.selfservice.kafka-janitor-consumer
        - name: KAFKA_JANITOR_BROKER_VERSION_FALLBACK
          value: "0.10.0.0"
        - name: KAFKA_JANITOR_API_VERSION_FALLBACK_MS
          value: "0"
        - name: KAFKA_JANITOR_SASL_USERNAME
          value: $(KAFKA_SASL_USERNAME)
        - name: KAFKA_JANITOR_SASL_PASSWORD
          value: $(KAFKA_SASL_PASSWORD)
        - name: KAFKA_JANITOR_SASL_MECHANISMS
          value: "PLAIN"
        - name: KAFKA_JANITOR_SECURITY_PROTOCOL
          value: "SASL_SSL"