---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-janitor
  namespace: selfservice
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(aws-account-id):role/PutKafkaParameter # replace with actual account id
    eks.amazonaws.com/sts-regional-endpoints: "true"
