apiVersion: v1
kind: Service
metadata:
  name: tika-lkc-4npj6
  namespace: $(kubernetes-namespace)
  labels:
    app: tika
    project: selfservice
    department: devex
    component: tika
    cluster: lkc-4npj6
    scrape-service-metrics: "true"
spec:
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
  selector:
    app: tika
    cluster: lkc-4npj6

---
apiVersion: v1
kind: Service
metadata:
  name: tika-lkc-3wqzw
  namespace: $(kubernetes-namespace)
  labels:
    app: tika
    project: selfservice
    department: devex
    component: tika
    cluster: lkc-3wqzw
    scrape-service-metrics: "true"
    release: kafka-multi-cluster-preview
spec:
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
  selector:
    app: tika
    cluster: lkc-3wqzw